# Generated by Django 5.1.4 on 2024-12-31 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balanceAfterTransactions', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transactionsType', models.IntegerField(choices=[('DEPOSIT', 'Deposits'), ('WITHDRAWAL', 'Withdrawal'), ('LOAN', 'Loan'), ('LOAN_PAID', 'Loan Paid')], null=True)),
                ('timestamps', models.DateTimeField(auto_now_add=True)),
                ('loanApprove', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='account.userbankaccount')),
            ],
            options={
                'ordering': ['timestamps'],
            },
        ),
    ]
