# Generated by Django 5.1.4 on 2025-01-04 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transactions',
            new_name='Transaction',
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['timestamp']},
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='balanceAfterTransactions',
            new_name='balance_after_transaction',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='loanApprove',
            new_name='loan_approve',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='timestamps',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transactionsType',
            new_name='transaction_type',
        ),
    ]
