# Generated by Django 5.1.4 on 2025-01-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankruft',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
